# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
user1 = User.create({ name: 'ferecamp', espol: 'ferecamp' })
user2 = User.create({ name: 'apinargo', espol: 'apinargo' })
user3 = User.create({ name: 'leras', espol: 'leras' })

user1.diagrams.create({name: 'Diagram Fer', image: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve"> <g class="entidad" id="entidad-0" x="0" y="0">            <g class="cuadrado" style="cursor:move">                <rect x="0" y="0" width="100" height="100" rx="0.5" ry="0.5" fill="#ffffff" stroke="#000000" style="-stroke-width: 2px;"/>            </g>            <g>                <rect x="0" y="0" width="100" height="30" rx="0.5" ry="0.5" fill="#ffffff" stroke="#000000" style="stroke-width: 2px;"/>                <text class="titulo" x="20" y="20">Entidad</text>                <circle class="closeButton" cx="100" cy="0" r="0" fill="#ff0000" stroke="#ff0000" style="stroke-width: 0px;"/>                <text class="atributo" x="10" y="50">Atributo</text>            </g>            <g class="line-handlers">                <circle class="handler-1" cx="50" cy="0" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-2" cx="100" cy="50" r="0" fill="#78BF24"  stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-3" cx="50" cy="100" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-4" cx="0" cy="50" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>            </g>        </g></svg>'})
user2.diagrams.create({name: 'Diagrama Adriano', image: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve"> <g class="entidad" id="entidad-0" x="0" y="0">            <g class="cuadrado" style="cursor:move">                <rect x="0" y="0" width="100" height="100" rx="0.5" ry="0.5" fill="#ffffff" stroke="#000000" style="-stroke-width: 2px;"/>            </g>            <g>                <rect x="0" y="0" width="100" height="30" rx="0.5" ry="0.5" fill="#ffffff" stroke="#000000" style="stroke-width: 2px;"/>                <text class="titulo" x="20" y="20">Entidad</text>                <circle class="closeButton" cx="100" cy="0" r="0" fill="#ff0000" stroke="#ff0000" style="stroke-width: 0px;"/>                <text class="atributo" x="10" y="50">Atributo</text>            </g>            <g class="line-handlers">                <circle class="handler-1" cx="50" cy="0" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-2" cx="100" cy="50" r="0" fill="#78BF24"  stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-3" cx="50" cy="100" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>                <circle class="handler-4" cx="0" cy="50" r="0" fill="#78BF24" stroke="#ff0000" style="stroke-width: 0px;"/>            </g>        </g></svg>'})
user3.diagrams.create({name: 'Diagrama Leonardo', image: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve"> </svg>'})
DiagramsUser.create(diagram_id: Diagram.find(3).id, user_id: user1.id, shared:true)
DiagramsUser.create(diagram_id: Diagram.find(1).id, user_id: user2.id, shared:true)
DiagramsUser.create(diagram_id: Diagram.find(2).id, user_id: user3.id, shared:true)